name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Use GNU Tar from Msys
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::add-path::C:\msys64\usr\bin"
          
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          test
        key: test-v8
        
    - name: Display content
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        du -a
        
    - name: Create content
      if: steps.cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        mkdir test
        cd test
        mkdir foo
        cd foo
        mkdir bar
        cd bar
        mklink /j link ..\..
