name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          test
        key: test-v6
        
    - name: Locate Mingw
      run: |
        echo %PATH%
        dir C:\msys64\
        dir C:\msys64\usr\bin
        dir C:\msys64\mingw32\bin
        dir C:\msys64\mingw64\bin
        
    - name: Add Mingw to PATH
      run: |
        echo "::add-path::C:\msys64\mingw64\bin"
      
    - name: Display content
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        du -a
        
    - name: Create content
      if: steps.cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        mkdir test
        cd test
        mkdir foo
        cd foo
        mkdir bar
        cd bar
        rem mklink /j link ..\..
        mklink /D link ..\..
