name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          test
        key: test-v2
        
    - name: Create content
      if: steps.cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        mkdir -p test/foo/bar
        mklink /j link ..\..
